# Site settings
title: Manuel Leduc
email: manuel.leduc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dev notes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://manuelleduc.github.io/" # the base hostname & protocol for your site
twitter_username: manuel_leduc
github_username:  manuelleduc

# Build settings
markdown: kramdown
